spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDR:geniussbg.cn:13306}/${MYSQL_DATABASE:seven_cow_cloud}?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:genius_server_0704}
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: ${REDIS_ADDR:geniussbg.cn} # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: ${REDIS_PORT:16379} # Redis服务器连接端口
    password: ${REDIS_PWD:keKEaiai5201314} # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  application:
    name: shineonce-review${UNIQUE_ID:0}-service
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:geniussbg.cn:18848}
      username: ${NACOS_SERVER_USER:nacos}
      password: ${NACOS_SERVER_PASSWORD:keKEaiai5201314}
      config:
        file-extension: yaml
      discovery:
        ip: ${SERVER_ADDR:geniussbg.cn}
  rabbitmq:
    host: ${MQ_ADDR:geniussbg.cn} # rabbitMQ的ip地址
    port: ${MQ_PORT:15672} # 端口
    username: ${MQ_USERNAME:root}
    password: ${MQ_PWD:genius_server_0704}
    virtual-host: /
    publisher-confirm-type: simple
    publisher-returns: true
    listener:
      simple:
        prefetch: ${MQ_PREFETCH:5}
        concurrency: ${MIN_CONCURRENCY:5}
        max-concurrency: ${MAX_CONCURRENCY:10}
        acknowledge-mode: manual
management:
  endpoints:
    web:
      exposure:
        include: '*'
